//
//  PromoViewController.swift
//  PromoCodeScreen
//
//  Created tambanco 🥳 on 13.03.2022.
//
//  Template generated by Tambanco
//

import UIKit

class PromoViewController: UIViewController {

	var presenter: PromoPresenterProtocol!

    @IBOutlet weak var promoTextField: UITextField!
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    @IBAction func confirmButtonPressed(_ sender: UIButton) {
        self.presenter.codeVerifier(userPromocode: promoTextField.text)
    }
}

// MARK: - Binding
extension PromoViewController: PromoViewProtocol {
    func setPromocode(promocode: String) {
    }
    
    func showAlert(result: Result) {
        if result == Result.success {
            let alert = UIAlertController(title: "Successfully", message: "Your promocode is correct!", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
        } else {
            let alert = UIAlertController(title: "Failure", message: "This promocode is unavailable!", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
        }
    }
}
