//
//  PromoViewController.swift
//  PromoCodeScreen
//
//  Created tambanco 🥳 on 13.03.2022.
//
//  Template generated by Tambanco
//

import UIKit

class PromoViewController: UIViewController {

	var presenter: PromoPresenterProtocol!

	override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}

// MARK: - Binding
extension PromoViewController: PromoViewProtocol {
    
}
